# Generated by Django 6.0.5 on 2026-05-22 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0002_initial'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('vida_util_anios', models.IntegerField(blank=True, null=True)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('en_uso', 'En Uso'), ('depreciado', 'Depreciado'), ('dado_baja', 'Dado de Baja'), ('mantenimiento', 'Mantenimiento')], default='en_uso', max_length=30)),
                ('id_planta', models.ForeignKey(blank=True, db_column='id_planta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos', to='erp.planta')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'db_table': 'activos_fijos',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_costo', to='security.departamento')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'db_table': 'centros_costo',
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('capital', 'Capital'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=30)),
                ('id_cuenta_padre', models.ForeignKey(blank=True, db_column='id_cuenta_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_hijas', to='finance.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'cuentas_contables',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_centro', models.ForeignKey(blank=True, db_column='id_centro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='finance.centrocosto')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transacciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('id_cuenta', models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_transaccion', to='finance.cuentacontable')),
                ('id_transaccion', models.ForeignKey(db_column='id_transaccion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='finance.transaccion')),
            ],
            options={
                'verbose_name': 'Detalle de Transacción',
                'verbose_name_plural': 'Detalles de Transacción',
                'db_table': 'detalle_transaccion',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('monto_planificado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('id_centro', models.ForeignKey(db_column='id_centro', on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='finance.centrocosto')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
                'constraints': [models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='mes_valid')],
            },
        ),
    ]
