# Generated by Django 6.0.5 on 2026-05-22 04:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaEnsamblaje',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='activa', max_length=30)),
            ],
            options={
                'verbose_name': 'Línea de Ensamblaje',
                'verbose_name_plural': 'Líneas de Ensamblaje',
                'db_table': 'lineas_ensamblaje',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('origen', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('motor', models.CharField(blank=True, max_length=50, null=True)),
                ('year_inicio', models.IntegerField(blank=True, null=True)),
                ('year_fin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modelo de Vehículo',
                'verbose_name_plural': 'Modelos de Vehículos',
                'db_table': 'modelos_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'plantas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='RobotIndustrial',
            fields=[
                ('id_robot', models.AutoField(primary_key=True, serialize=False)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('version_software', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_actualizacion', models.DateField(blank=True, null=True)),
                ('contacto_soporte', models.CharField(blank=True, max_length=150, null=True)),
                ('notas_versiones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Robot Industrial',
                'verbose_name_plural': 'Robots Industriales',
                'db_table': 'robots_industriales',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_material', models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='erp.material')),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='erp.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_planificada', models.IntegerField()),
                ('cantidad_producida', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('id_linea', models.ForeignKey(db_column='id_linea', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='erp.lineaensamblaje')),
                ('id_modelo', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='erp.modelovehiculo')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'db_table': 'ordenes_produccion',
            },
        ),
    ]
