# Generated by Django 6.0.5 on 2026-05-22 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_produccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planta',
            name='id_gerente',
            field=models.ForeignKey(blank=True, db_column='id_gerente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineaensamblaje',
            name='id_planta',
            field=models.ForeignKey(db_column='id_planta', on_delete=django.db.models.deletion.CASCADE, related_name='lineas_ensamblaje', to='erp.planta'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='erp.proveedor'),
        ),
        migrations.AddField(
            model_name='robotindustrial',
            name='id_planta',
            field=models.ForeignKey(db_column='id_planta', on_delete=django.db.models.deletion.CASCADE, related_name='robots_industriales', to='erp.planta'),
        ),
    ]
