# Generated by Django 6.0.5 on 2026-05-22 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDefinicion',
            fields=[
                ('id_kpi', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Definición de KPI',
                'verbose_name_plural': 'Definiciones de KPI',
                'db_table': 'kpi_definiciones',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario_destino', models.ForeignKey(db_column='id_usuario_destino', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaOperacion',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(blank=True, max_length=80, null=True)),
                ('operacion', models.CharField(blank=True, choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Operación',
                'verbose_name_plural': 'Auditorías de Operaciones',
                'db_table': 'auditoria_operaciones',
            },
        ),
        migrations.CreateModel(
            name='KPIValor',
            fields=[
                ('id_valor', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('meta', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_kpi', models.ForeignKey(db_column='id_kpi', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='bi.kpidefinicion')),
            ],
            options={
                'verbose_name': 'Valor de KPI',
                'verbose_name_plural': 'Valores de KPI',
                'db_table': 'kpi_valores',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('query_base', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_creador', models.ForeignKey(blank=True, db_column='id_creador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
            },
        ),
    ]
