# Generated by Django 6.0.5 on 2026-05-22 04:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('persona', 'Persona Natural'), ('empresa', 'Empresa')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'db_table': 'detalle_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id_distribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
                'db_table': 'distribuidores',
            },
        ),
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('id_interaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunión'), ('seguimiento', 'Seguimiento'), ('otros', 'Otros')], max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Interacción de Cliente',
                'verbose_name_plural': 'Interacciones de Clientes',
                'db_table': 'interacciones_cliente',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('anulada', 'Anulada')], default='activa', max_length=30)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='borrador', max_length=30)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
            },
        ),
    ]
