# Generated by Django 6.0.5 on 2026-05-22 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('erp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='id_cotizacion',
            field=models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='crm.cotizacion'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='id_modelo',
            field=models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='erp.modelovehiculo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_distribuidor',
            field=models.ForeignKey(blank=True, db_column='id_distribuidor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='crm.distribuidor'),
        ),
        migrations.AddField(
            model_name='interaccioncliente',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.cliente'),
        ),
        migrations.AddField(
            model_name='interaccioncliente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='crm.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_cotizacion',
            field=models.ForeignKey(blank=True, db_column='id_cotizacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='crm.cotizacion'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
