# Generated by Django 6.0.5 on 2026-05-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0002_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('duracion_horas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'db_table': 'capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('salario_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'puestos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('dpi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('email_corporativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('operario', 'Operario'), ('administrativo', 'Administrativo'), ('mercadeo', 'Mercadeo'), ('ejecutivo', 'Ejecutivo')], max_length=30)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'Licencia'), ('jubilado', 'Jubilado')], default='activo', max_length=20)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='security.departamento')),
                ('id_planta', models.ForeignKey(blank=True, db_column='id_planta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='erp.planta')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id_planilla', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='planillas', to='hr.empleado')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'db_table': 'planilla',
            },
        ),
        migrations.CreateModel(
            name='HistorialPuesto',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_puestos', to='hr.empleado')),
                ('id_puesto', models.ForeignKey(db_column='id_puesto', on_delete=django.db.models.deletion.PROTECT, related_name='historial_empleados', to='hr.puesto')),
            ],
            options={
                'verbose_name': 'Historial de Puesto',
                'verbose_name_plural': 'Historial de Puestos',
                'db_table': 'historial_puestos',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('id_capacitacion', models.ForeignKey(db_column='id_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='hr.capacitacion')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='hr.empleado')),
            ],
            options={
                'verbose_name': 'Empleado-Capacitación',
                'verbose_name_plural': 'Empleado-Capacitaciones',
                'db_table': 'empleado_capacitacion',
                'unique_together': {('id_empleado', 'id_capacitacion')},
            },
        ),
    ]
