# Generated by Django 6.0.5 on 2026-05-22 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id_servidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=80, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_datacenter', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='activo', max_length=30)),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'servidores',
            },
        ),
        migrations.CreateModel(
            name='PlanContinuidad',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_ultima_prueba', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('en_revision', 'En Revisión'), ('obsoleto', 'Obsoleto'), ('archivado', 'Archivado')], default='vigente', max_length=30)),
                ('id_responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_continuidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Continuidad',
                'verbose_name_plural': 'Planes de Continuidad',
                'db_table': 'plan_continuidad',
            },
        ),
        migrations.CreateModel(
            name='RiesgoTI',
            fields=[
                ('id_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('probabilidad', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, null=True)),
                ('impacto', models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20, null=True)),
                ('nivel_riesgo', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_mitigacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mitigado', 'Mitigado'), ('resuelto', 'Resuelto'), ('inactivo', 'Inactivo')], default='activo', max_length=30)),
                ('id_responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riesgo TI',
                'verbose_name_plural': 'Riesgos TI',
                'db_table': 'riesgos_ti',
            },
        ),
        migrations.CreateModel(
            name='SistemaInformatico',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=80, null=True)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('ubicacion_servidor', models.CharField(blank=True, max_length=100, null=True)),
                ('tiene_codigo_fuente', models.BooleanField(default=False)),
                ('tiene_backup', models.BooleanField(default=False)),
                ('criticidad', models.CharField(blank=True, choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento'), ('descontinuado', 'Descontinuado')], default='activo', max_length=30)),
                ('id_responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sistemas_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sistema Informático',
                'verbose_name_plural': 'Sistemas Informáticos',
                'db_table': 'sistemas_informaticos',
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoRecuperacion',
            fields=[
                ('id_procedimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('pasos', models.TextField(blank=True, null=True)),
                ('rto_horas', models.IntegerField(blank=True, null=True)),
                ('rpo_horas', models.IntegerField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='it_management.plancontinuidad')),
                ('id_sistema', models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_recuperacion', to='it_management.sistemainformatico')),
            ],
            options={
                'verbose_name': 'Procedimiento de Recuperación',
                'verbose_name_plural': 'Procedimientos de Recuperación',
                'db_table': 'procedimientos_recuperacion',
            },
        ),
        migrations.CreateModel(
            name='IncidenteTI',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('impacto', models.CharField(blank=True, choices=[('critico', 'Crítico'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=30, null=True)),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=30)),
                ('id_usuario_reporte', models.ForeignKey(blank=True, db_column='id_usuario_reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
                ('id_sistema', models.ForeignKey(blank=True, db_column='id_sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='it_management.sistemainformatico')),
            ],
            options={
                'verbose_name': 'Incidente TI',
                'verbose_name_plural': 'Incidentes TI',
                'db_table': 'incidentes_ti',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('completo', 'Completo'), ('incremental', 'Incremental'), ('diferencial', 'Diferencial')], max_length=30, null=True)),
                ('fecha_backup', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
                ('id_servidor', models.ForeignKey(blank=True, db_column='id_servidor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='it_management.servidor')),
                ('id_sistema', models.ForeignKey(db_column='id_sistema', on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='it_management.sistemainformatico')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
            },
        ),
    ]
